### ISSUE TITLE
PHP Bug when requesting hotel_performance_view.conversions

### ISSUE THREAD

**Issue by roydidier** [googleads/google-ads-php#204]
PHP error requesting hotel_performance_view.conversions
(without conversions in the request it is working)
the error occurs before PHP send the request to Google. There is nothing in GoogleAdsApi.log.
Same error with V1 or V2

This is the request failing :
SELECT campaign.id,campaign.name,campaign.advertising_channel_type,segments.date,metrics.clicks,metrics.conversions FROM hotel_performance_view WHERE segments.date >= '2019-08-07' and segments.date <= '2019-09-05' and campaign.advertising_channel_type = 'HOTEL'

this is the error I get :
PHP Fatal error:  Uncaught Exception: Expect float. in /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:182
Stack trace:
#0 /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/DoubleValue.php(61): Google\Protobuf\Internal\GPBUtil::checkDouble(Object(Google\Protobuf\DoubleValue))
#1 /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1009): Google\Protobuf\DoubleValue->setValue(Object(Google\Protobuf\DoubleValue))
#2 /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(79): Google\Protobuf\Internal\Message->mergeFromArray(Array)
#3 /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/DoubleValue.php(38): Google\Protobuf\Internal\Message->__construct(Array)
#4 /home/metaio-dev-v5/google-ads-php/V2/src/Google/Ads/GoogleAds/V1/Common/Metrics.php(3960): Google\Protobuf\DoubleValue->__construct(Array)
#5 /home/metaio-dev-v5/goo in /home/metaio-dev-v5/google-ads-php/V2/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php on line 182

thanks

**Comment by PierrickVoulet** [comment]
Hi - I think it is related to the response decoding, could you provide your Customer ID?

**Comment by PierrickVoulet** [comment]
Closing this issue because of inactivity.
