### ISSUE TITLE
GPBDecodeException thrown for any failure from ConversionUploadServiceClient::uploadClickConversions()

### ISSUE THREAD

**Issue by villermen** [googleads/google-ads-php#210]
Whenever uploading click conversions fails for any reason I will get a Protocol Buffers exception about a missing `GoogleAdsFailure` class, hiding the real error. With some hacking in library code I am able to dump the real reason behind the error, but it would be great if the internal error handling would work correctly.

```
Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Class google.ads.googleads.v2.errors.GoogleAdsFailure hasn't been added to descriptor pool
/code/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1256
#0 /code/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(742): Google\Protobuf\Internal\Message->parseFromJsonStream(Object(Google\Protobuf\Internal\RawInputStream))
#1 /code/vendor/google/gax/src/Transport/RestTransport.php(118): Google\Protobuf\Internal\Message->mergeFromJsonString('{\n  "partialFai...')
#2 /code/vendor/guzzlehttp/promises/src/Promise.php(203): Google\ApiCore\Transport\RestTransport->Google\ApiCore\Transport\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /code/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#4 /code/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run()
#6 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /code/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /code/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /code/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /code/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /code/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /code/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V2/Services/Gapic/ConversionUploadServiceGapicClient.php(234): GuzzleHttp\Promise\Promise->wait()
#13 /code/module/Pro/src/Pro/Service/GoogleConversionService.php(98): Google\Ads\GoogleAds\V2\Services\Gapic\ConversionUploadServiceGapicClient->uploadClickConversions('[hidden]', Array, Array)
```

**Comment by PierrickVoulet** [comment]
Thank you for sharing this. We reproduced the issue and will continue working on this to identify the root cause and to fix it.

In the meantime, I noticed that you use the REST transport and not the gRPC transport: could you confirm it is intended?

**Comment by villermen** [comment]
@PierrickVoulet Thanks for the swift response.

I take it the REST transport is used as a fallback due to me not having installed the `grpc` and `protobuf` PECL extensions? Are there considerable downsides to keeping it this way? We're not doing anything performance-critical with the library and I figured that if it works this way it is less trouble to update both our environments.
