### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\ArgumentParser' not found 

### ISSUE THREAD

**Issue by shihabx7** [googleads/google-ads-php#286]
**Which version of the client library are you using?* 201809*

**Which version of PHP are you using?*7.4*

**Which operating system (Linux, Windows, ...) and version?*windows*

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
 $options = (new ArgumentParser())->parseCommandArguments([
            ArgumentNames::CUSTOMER_ID => GetOpt::REQUIRED_ARGUMENT,
            ArgumentNames::LOCATION_ID => GetOpt::MULTIPLE_ARGUMENT,
            ArgumentNames::LANGUAGE_ID => GetOpt::REQUIRED_ARGUMENT,
            ArgumentNames::KEYWORD_TEXT => GetOpt::MULTIPLE_ARGUMENT,
            ArgumentNames::PAGE_URL => GetOpt::OPTIONAL_ARGUMENT,
        ]);
**Expected result**

**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging)).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by PierrickVoulet** [comment]
@shihabx7 I think you are using the AdWords client library for PHP because of the version `201809` and not the Google Ads client library for PHP (this project), could you confirm and open a bug to the right project instead ([googleads-php-lib](https://github.com/googleads/googleads-php-lib))?

**Comment by shihabx7** [comment]
I use composer to get google-ads-api client library in my project and try to play with example files located in github. i think i'm using latest version.
other examples are run without any error.
but generateKeywordIdeas.php file throw an error.


  here i submit screenshot of my project 
![pln1](https://user-images.githubusercontent.com/21012068/76285377-d46bbb00-62c9-11ea-95b5-93b58c1eea25.png)

**Comment by PierrickVoulet** [comment]
I am suspecting an environment setup issue: I see that you use the GetCampaigns code example and it uses the ArgumentParser class too.

Could you provide the relevant part(s) of the composer.json content?

**Comment by fiboknacky** [comment]
Closing due to inactivity. Feel free to reopen if you still face with this issue.

**Comment by GitHubgopinath** [comment]
Hi ,Iam working with google ads iam gettings this error,please help me

Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\examples\Utils\ArgumentParser' not found in C:\xampp\htdocs\googleads\CreateCustomer.php:48 Stack trace: #0 C:\xampp\htdocs\googleads\CreateCustomer.php(128): Google\Ads\GoogleAds\examples\AccountManagement\CreateCustomer::main() #1 {main} thrown in C:\xampp\htdocs\googleads\CreateCustomer.php on line 48

**Comment by PierrickVoulet** [comment]
> Hi ,Iam working with google ads iam gettings this error,please help me
> 
> Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\examples\Utils\ArgumentParser' not found in C:\xampp\htdocs\googleads\CreateCustomer.php:48 Stack trace: #0 C:\xampp\htdocs\googleads\CreateCustomer.php(128): Google\Ads\GoogleAds\examples\AccountManagement\CreateCustomer::main() #1 {main} thrown in C:\xampp\htdocs\googleads\CreateCustomer.php on line 48

Hi @GitHubgopinath I created a new [issue](https://github.com/googleads/google-ads-php/issues/464) because this one was closed.

**Comment by divyeshgajja** [comment]
**Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\ArgumentParser' not found**  
i am also facing same issue im already get code from composer still same error .
kindly please help me how to solve this.

**Comment by PierrickVoulet** [comment]
> **Fatal error: Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\ArgumentParser' not found**
> i am also facing same issue im already get code from composer still same error .
> kindly please help me how to solve this.

Hi @divyeshgajja I created a new [issue](https://github.com/googleads/google-ads-php/issues/564) because this one was closed a long time ago.

**Comment by divyeshgajja** [comment]
already created kindly plz check..
https://github.com/googleads/google-ads-php/issues/563
