### ISSUE TITLE
GuzzleHttp\Exception\ConnectException fopen:Too many open files

### ISSUE THREAD

**Issue by cgunnels** [googleads/google-ads-php#551]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**What versions of the client library and Google Ads API are you using?**
google/apiclient                          v2.9.1     Client library for Google APIs
google/apiclient-services                 v0.162.0   Client library for Google APIs
google/auth                               v1.15.0    Google Auth Library for PHP
google/common-protos                      1.3        Google API Common Protos for PHP
google/gax                                1.7.0      Google API Core for PHP
google/grpc-gcp                           0.1.5      gRPC GCP library for channel management
google/protobuf                           v3.15.3    proto library for PHP
googleads/google-ads-php                  v5.0.0     Google Ads API client for PHP
socialiteproviders/google                 v3.1.0     Google OAuth2 Provider for Laravel Socialite
guzzlehttp/guzzle                         6.5.5      Guzzle is a PHP HTTP client library
guzzlehttp/promises                       1.4.0      Guzzle promises library
guzzlehttp/psr7                           1.7.0      PSR-7 message implementation that also provides common utility methods
http-interop/http-factory-guzzle          1.0.0      An HTTP Factory using Guzzle PSR7

**What environment are you using?**
PHP 7.4.1
laravel/framework                         v5.8.38    The Laravel Framework.
Linux efde14b267ee 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64

**Actions taken**
$googleAdsClient is an instance of `GoogleAdsClient`
I run `$googleAdsClient->getGoogleAdsServiceClient()->search($customerId, $query, $page_size);`

**Expected result**
The search results should be returned

**Actual result**
The GuzzleHttp\Exception\ConnectException to many files open error.

 
**Anything else we should know about your project / environment**
Stack trace:
```
GuzzleHttp\Exception\ConnectException: cURL error 35: error:02001018:system library:fopen:Too many open files (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
#67 /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(200): GuzzleHttp\Handler\CurlFactory::createRejection
#66 /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::finishError
#65 /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finish
#64 /vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlHandler::__invoke
#63 /vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}
#62 /vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}
#61 /vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\PrepareBodyMiddleware::__invoke
#60 /vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#59 /vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\RedirectMiddleware::__invoke
#58 /vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#57 /vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\HandlerStack::__invoke
#56 /vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\Client::transfer
#55 /vendor/guzzlehttp/guzzle/src/Client.php(112): GuzzleHttp\Client::sendAsync
#54 /vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client::send
#53 /vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(47): Google\Auth\HttpHandler\Guzzle6HttpHandler::__invoke
#52 /vendor/google/auth/src/OAuth2.php(526): Google\Auth\OAuth2::fetchAuthToken
#51 /vendor/google/auth/src/Credentials/UserRefreshCredentials.php(110): Google\Auth\Credentials\UserRefreshCredentials::fetchAuthToken
#50 /vendor/google/auth/src/CredentialsLoader.php(241): Google\Auth\CredentialsLoader::updateMetadata
#49 /vendor/google/gax/src/CredentialsWrapper.php(197): Google\ApiCore\CredentialsWrapper::Google\ApiCore\{closure}
#48 [internal](0): Grpc\Call::startBatch
#47 /vendor/grpc/grpc/src/lib/UnaryCall.php(44): Grpc\UnaryCall::start
#46 /vendor/grpc/grpc/src/lib/BaseStub.php(291): Grpc\BaseStub::Grpc\{closure}
#45 /vendor/grpc/grpc/src/lib/BaseStub.php(541): Grpc\BaseStub::_simpleRequest
#44 /vendor/google/gax/src/Transport/GrpcTransport.php(213): Google\ApiCore\Transport\GrpcTransport::startUnaryCall
#43 /vendor/google/gax/src/GapicClientTrait.php(511): Google\Ads\GoogleAds\V5\Services\Gapic\GoogleAdsServiceGapicClient::Google\ApiCore\{closure}
#42 /vendor/google/gax/src/Middleware/CredentialsWrapperMiddleware.php(61): Google\ApiCore\Middleware\CredentialsWrapperMiddleware::__invoke
#41 /vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\FixedHeaderMiddleware::__invoke
#40 /vendor/google/gax/src/Middleware/RetryMiddleware.php(88): Google\ApiCore\Middleware\RetryMiddleware::__invoke
#39 /vendor/google/gax/src/Middleware/OptionsFilterMiddleware.php(63): Google\ApiCore\Middleware\OptionsFilterMiddleware::__invoke
#38 /vendor/google/gax/src/Middleware/PagedMiddleware.php(67): Google\ApiCore\Middleware\PagedMiddleware::__invoke
#37 /vendor/google/gax/src/Middleware/FixedHeaderMiddleware.php(66): Google\ApiCore\Middleware\FixedHeaderMiddleware::__invoke
#36 /vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V5/UnaryGoogleAdsExceptionMiddleware.php(63): Google\Ads\GoogleAds\Lib\V5\UnaryGoogleAdsExceptionMiddleware::__invoke
#35 /vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V5/UnaryGoogleAdsResponseMetadataCallable.php(64): Google\Ads\GoogleAds\Lib\V5\UnaryGoogleAdsResponseMetadataCallable::__invoke
#34 /vendor/google/gax/src/GapicClientTrait.php(629): Google\Ads\GoogleAds\V5\Services\Gapic\GoogleAdsServiceGapicClient::getPagedListResponse
#33 /vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V5/Services/Gapic/GoogleAdsServiceGapicClient.php(285): Google\Ads\GoogleAds\V5\Services\Gapic\GoogleAdsServiceGapicClient::search
```

**Comment by fiboknacky** [comment]
Could you update the library to the latest version and try again?
A newer version of grpc might be able to resolve this issue. If not, we probably need to look into grpc.

**Comment by fiboknacky** [comment]
Closing due to inactivity.
