### ISSUE TITLE
Upgrading to V10 errors

### ISSUE THREAD

**Issue by stephenvm** [googleads/google-ads-php#801]
* Client library version: `v8.1.0`
* Google Ads API version: `V8`

**Your environment:**
PHP Version 7.3.33
Protobuf and grpc is not installed, but up to this point, I didn't need them

**Description of the bug:**
I'm trying to upgrade to V10, and I got info to upload V10 files within the src/Google/Ads/GoogleAds directory. I cloned the entire library and uploaded the V10 files and got the following Errors:

Uncaught Error: Class 'GPBMetadata\Google\Ads\GoogleAds\V10\Errors\Errors' not found in /home/XXXX/public_html/luck/google-ads-php/src/Google/Ads/GoogleAds/V10/Errors/GoogleAdsFailure.php:45
Stack trace: #0 /home/XXXX/public_html/luck/google-ads-php/src/Google/Ads/GoogleAds/Util/V10/GoogleAdsFailures.php(92): Google\Ads\GoogleAds\V10\Errors\GoogleAdsFailure-&gt;__construct()
#1 /home/XXXX/public_html/luck/google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/GoogleAdsClient.php(59): Google\Ads\GoogleAds\Util\V10\GoogleAdsFailures::init()
#2 /home/XXXX/public_html/luck/google-ads-php/src/Google/Ads/GoogleAds/Lib/V10/GoogleAdsClientBuilder.php(328): Google\Ads\GoogleAds\Lib\V10\GoogleAdsClient-&gt;__construct(Object(Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder))
#3 /home/XXXX/public_html/luck/google-ads-php/getkeywords.php(34): Google\Ads\GoogleAds\Lib\V10\GoogleAdsClientBuilder-&gt;build()
#4 /home/XXXX/public_html/luck/google-ads-php/getkeywords.php(151): GetKeywordIdeas::main()
#5 {main} th in <b>/home/XXXX/public_html/luck/google-ads-php/src/Google/Ads/GoogleAds/V10/Errors/GoogleAdsFailure.php</b> on line <b>45</b>

Do I need to upload the entire library to fix this issue? I'm using this library to get Keyword Ideas only.

**Comment by PierrickVoulet** [comment]
Hi @stephenvm - We [added support for Google Ads API V10](https://github.com/googleads/google-ads-php/blob/main/CHANGELOG.md#1400) in [the version 14.0.0 of this client library](https://github.com/googleads/google-ads-php/releases/tag/v14.0.0). Upgrading to this version or a newer one should do the trick, could you try and let us know?

**Comment by PierrickVoulet** [comment]
Not sure how you manage your application dependencies but the recommendation is to rely on `composer`.

* If you use `composer` you could require the version `14.0.0` or a newer one for the dependency `googleads/google-ads-php`, [here](https://github.com/googleads/google-ads-php/blob/main/examples/LaravelSampleApp/composer.json#L13) is an example.
* Otherwise you should re-upload the entire library source code provided for each [release](https://github.com/googleads/google-ads-php/releases).

**Comment by stephenvm** [comment]
Can I add "googleads/google-ads-php": ">=13.0" to the root composer.json file within the require section? Or does it have to be within the LaravelSampleApp?

**Comment by PierrickVoulet** [comment]
If your application uses `composer`, adding `"googleads/google-ads-php": ">=14.0"` in the `require` section of the `composer.json` file of your application and running `composer update` should be enough.

The `LaravelSampleApp` is just an example of an application that uses our library, you do not need to edit it. The link I provided was just an example to show know an application can require the library with a version constraints using `composer`.

**Comment by PierrickVoulet** [comment]
Closing this issue due to inactivity.
