### ISSUE TITLE
Update sitelink asset

### ISSUE THREAD

**Issue by shobha-procentris** [googleads/google-ads-php#834]
Hi,

Using the PHP library when we are trying to update the description of sitelink using PHP library

We are getting the following error

Array
(
    [type] => 1
    [message] => Uncaught TypeError: Argument 1 passed to Google\Ads\GoogleAds\Util\FieldMasks::allSetFieldsOf() must be an instance of Google\Protobuf\Internal\Message, array given, called in /var/www/sites/psmedia/perfectstormmedia/tools/campaign-settings/sitelinks-new/sitelinkSettings.class.php on line 1039 and defined in /var/www/sites/psmedia/perfectstormmedia/tools/includes/api/google-ads-php/src/Google/Ads/GoogleAds/Util/FieldMasks.php:102
Stack trace:
#0 /var/www/sites/psmedia/perfectstormmedia/tools/campaign-settings/sitelinks-new/sitelinkSettings.class.php(1039): Google\Ads\GoogleAds\Util\FieldMasks::allSetFieldsOf(Array)
#1 /var/www/sites/psmedia/perfectstormmedia/tools/campaign-settings/sitelinks-new/manage-sitelink-feed-submit.php(195): sitelinkSettings->addEditSitelinkFeedItem('[3087510920](tel:(308)%20751-0920)', Array, 'SET')
#2 {main}
  thrown
    [file] => /var/www/sites/psmedia/perfectstormmedia/tools/includes/api/google-ads-php/src/Google/Ads/GoogleAds/Util/FieldMasks.php
    [line] => 102
)

 $assetId = $itemDetails['feedId'];
        // Creates an operation to add each asset.
        $assetOperations = new AssetOperation();
        $assetOperations->setUpdate(`customers/$adwordsId/assets/$assetId`,$assets);
        $assetOperations->setUpdateMask(`customers/$adwordsId/assets/$assetId`,FieldMasks::allSetFieldsOf($assets));

Can you please let us know how can we update sitelink asset as we are finding it difficult. We checked that the protobuf installation is fine

Thanks,
Anil

**Comment by shobha-procentris** [comment]
Thank you Pierrick for the reply. We are trying to update only one asset(sitelink here). Not sure if this is the correct way, if you can please guide it would be of great great help..The code which we are using us as mentioned below:

function addEditSitelinkFeedItem($adwordsId, $itemDetails, $action)
    {
        parent::setAdwordsClientAccount($adwordsId);

        // Creates some sitelink assets.
        $sitelinkAsset = new SitelinkAsset([
            'description1' => 'test Description 1',
            'description2' => 'test Description 2',
            'link_text' => 'test Headline'
        ]);
        
        // Wraps the sitelinks in an Asset and sets the URLs.
        $assets = [
            new Asset([
                'sitelink_asset' => $sitelinkAsset,
                'final_urls' => 'https://test.com/final', // passed in itemDetails at the top
                'final_mobile_urls' => 'https://test.com/final2', // passed in itemDetails at the top
                'tracking_url_template' => trim($itemDetails['trackingUrl']) // passed in itemDetails at the top
            ]),
        ];
        
        $assetId = $itemDetails['feedId'];
        // Creates an operation to add each asset.
        $assetOperations = new AssetOperation();
        $assetOperations->setUpdate(`customers/$adwordsId/assets/$assetId`,$assets);
        $assetOperations->setUpdateMask(`customers/$adwordsId/assets/$assetId`,FieldMasks::allSetFieldsOf($assets));
   }

Please let us know what needs to be corrected so that we can update the sitelink ( description/final url/ etc )

Thanks,
Shobha

**Comment by PierrickVoulet** [comment]
Your variable `$assets` is an array. You should only edit one asset in an operation so you should change the following:

```php
$assets = [
        new Asset([
            ...
        ]),
    ];
```

to the following:

```php
$assets = new Asset([
    ...
]);
```

**Comment by fiboknacky** [comment]
Closing due to inactivity. Feel free to reopen this if you still face the issue.
