### ISSUE TITLE
Switching from V13 to V15 & getting error while uploading click conversion

### ISSUE THREAD

**Issue by AlanTY125** [googleads/google-ads-php#973]
Hi,

 I am using PHP version 8.1 and PHP client library for the Google Ads API "googleads/google-ads-php": "^21.1".
 Used the following code to create an instance of GoogleAdsClient Object

 $oAuth2Credential = (new OAuth2TokenBuilder())
                    ->withClientId($this->app_client_id)
                    ->withClientSecret($this->app_client_secret)
                    ->withRefreshToken($this->refreshtoken)
                    ->build();
$googleAdsClient = (new GoogleAdsClientBuilder())
		    ->withDeveloperToken($this->developerToken)
		    ->withOAuth2Credential($oAuth2Credential)
		    ->withLoginCustomerId($this->customerId)
		    ->usingGapicV2Source(true)
		    ->build();
		   
After that, i used the code in the following URL to create a conversion action

[https://developers.google.com/google-ads/api/docs/conversions/upload-clicks](https://developers.google.com/google-ads/api/docs/conversions/upload-clicks)

**conversion action was created successfully**, after I used the code on the same page to **insert a conversion** into that conversion action, and I'm facing the following error		   

TypeError: Google\ApiCore\Middleware\RetryMiddleware::Google\ApiCore\Middleware\{closure}(): Argument #1 ($e) must be of type Exception, Error given, called in /var/www/html/v5projects/googleads2024/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 109 in file /var/www/html/v5projects/googleads2024/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 183

**Comment by fiboknacky** [comment]
Could you update all dependencies and try again?
If the issue persists, could you share the versions of other dependencies, such as `gax` and `protobuf`?

**Comment by AlanTY125** [comment]
Updated the dependencies and still the same error
gax version: 1.25.0
google/protobuf : v3.25.1

**Comment by fiboknacky** [comment]
It looks like this is an issue on [`gax-php`](https://github.com/googleapis/gax-php/blob/v1.25.0/src/Middleware/RetryMiddleware.php).
I'd need more information to help the owner of that library fix this.

Could you please share your request and response logs by posting on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?
Let the agents there know that you want to share the request and response logs privately to "the PHP client library owner". They'll provide you instructions and pass the data to me.

**Comment by psociety** [comment]
I can replicate the error with:
```php

use Google\Ads\GoogleAds\Lib\V15\GoogleAdsClient;
use Google\Ads\GoogleAds\Util\V15\ResourceNames;
use Google\Ads\GoogleAds\V15\Services\KeywordAndUrlSeed;
use Google\Ads\GoogleAds\V15\Services\KeywordSeed;
use Google\Ads\GoogleAds\V15\Services\UrlSeed;
use Google\Ads\GoogleAds\V15\Enums\KeywordPlanNetworkEnum\KeywordPlanNetwork;

function generateKeywords(
        array $locationIds,
        int $languageId,
        array $keywords,
        ?string $pageUrl = null
    ) {
        $keywordPlanIdeaServiceClient = $this->googleAdsClient->getKeywordPlanIdeaServiceClient();

        // Make sure that keywords and/or page URL were specified. The request must have exactly one
        // of urlSeed, keywordSeed, or keywordAndUrlSeed set.
        if (empty($keywords) && is_null($pageUrl)) {
            throw new \InvalidArgumentException(
                'At least one of keywords or page URL is required, but neither was specified.'
            );
        }

        // Specify the optional arguments of the request as a keywordSeed, urlSeed,
        // or keywordAndUrlSeed.
        $requestOptionalArgs = [];
        if (empty($keywords)) {
            // Only page URL was specified, so use a UrlSeed.
            $requestOptionalArgs['urlSeed'] = new UrlSeed(['url' => $pageUrl]);
        } elseif (is_null($pageUrl)) {
            // Only keywords were specified, so use a KeywordSeed.
            $requestOptionalArgs['keywordSeed'] = new KeywordSeed(['keywords' => $keywords]);
        } else {
            // Both page URL and keywords were specified, so use a KeywordAndUrlSeed.
            $requestOptionalArgs['keywordAndUrlSeed'] =
                new KeywordAndUrlSeed(['url' => $pageUrl, 'keywords' => $keywords]);
        }

        // Create a list of geo target constants based on the resource name of specified location
        // IDs.
        $geoTargetConstants = array_map(function ($locationId) {
            return ResourceNames::forGeoTargetConstant($locationId);
        }, $locationIds);

        // Generate keyword ideas based on the specified parameters.
        $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
            [
                // Set the language resource using the provided language ID.
                'language' => ResourceNames::forLanguageConstant($languageId),
                'customerId' => self::CUSTOMER_ID,
                // Add the resource name of each location ID to the request.
                'geoTargetConstants' => $geoTargetConstants,
                // Set the network. To restrict to only Google Search, change the parameter below to
                // KeywordPlanNetwork::GOOGLE_SEARCH.
                'keywordPlanNetwork' => KeywordPlanNetwork::GOOGLE_SEARCH_AND_PARTNERS
            ] + $requestOptionalArgs
        );

        $list = [];

        // Iterate over the results and print its detail.
        foreach ($response->iterateAllElements() as $result) {
            $list[] = $result->getText();
            /*
            printf(
                "Keyword idea text '%s' has %d average monthly searches and competition as %d.%s",
                $result->getText(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getAvgMonthlySearches(),
                is_null($result->getKeywordIdeaMetrics()) ?
                    0 : $result->getKeywordIdeaMetrics()->getCompetition(),
                PHP_EOL
            );*/
        }

        return $list;
    }


$list = generateKeywords([2250], 1002, ["test"]);
```

the function is copied from the sample on the doc.

**Comment by fiboknacky** [comment]
Hello @psociety,

Thanks for more information.

> Call to undefined function Google\Protobuf\Internal\bccomp()

At what line of what repository (this library or `gax-php`) do you see this error message?

**Comment by AlanTY125** [comment]
Error I am getting is

Fatal error: Uncaught TypeError: Google\ApiCore\Middleware\RetryMiddleware::Google\ApiCore\Middleware\{closure}(): Argument #1 ($e) must be of type Exception, Error given, called in /var/www/html/v5projects/myproject/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 109 and defined in /var/www/html/v5projects/myproject/vendor/google/gax/src/Middleware/RetryMiddleware.php:183 Stack trace: #0 /var/www/html/v5projects/myproject/vendor/google/gax/src/Middleware/RetryMiddleware.php(109): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware\{closure}() #1 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(209): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware\{closure}() #2 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/v5projects/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/html/v5projects/myproject/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick() #6 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute() #7 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #8 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #10 /var/www/html/v5projects/myproject/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #11 /var/www/html/v5projects/myproject/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V15/Services/Client/ConversionUploadServiceClient.php(285): GuzzleHttp\Promise\Promise->wait() #12 /var/www/html/v5projects/myproject/UploadOfflineConversion.php(261): Google\Ads\GoogleAds\V15\Services\Client\ConversionUploadServiceClient->uploadClickConversions() #13 /var/www/html/v5projects/myproject/UploadOfflineConversion.php(136): UploadOfflineConversion\UploadOfflineConversion::runExample() #14 /var/www/html/v5projects/myproject/UploadOfflineConversion.php(289): UploadOfflineConversion\UploadOfflineConversion::main() #15 {main} thrown in /var/www/html/v5projects/myproject/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 183

**Comment by sebastianoSali** [comment]
I have same error on cloud-speech package.

**Comment by huyleresonancetech** [comment]
I am facing the same problem. Both my server and local server are running php version 8.0.30, it runs fine on my local machine. when i run it on the server it gives the same error. 

TypeError: Google\ApiCore\Middleware\RetryMiddleware::Google\ApiCore\Middleware\{closure}(): Argument #1 ($e) must be of type Exception, Error given, called in /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 109 and defined in /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php:183
Stack trace:
#0 /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php(109): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware\{closure}()
#1 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(209): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware\{closure}()
#2 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler()
#3 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/myproject/public/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run()
#5 /home/myproject/public/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute()
#7 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /home/myproject/public/laravel/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php(405): GuzzleHttp\Promise\Promise->wait()
#12 /home/myproject/public/laravel/modules/seo-core/src/Services/Keyword/Resources/GoogleAds/KeywordPlanIdeaService.php(223): Google\Ads\GoogleAds\V14\Services\Gapic\KeywordPlanIdeaServiceGapicClient->generateKeywordHistoricalMetrics()
#13 /home/myproject/public/laravel/modules/seo-core/src/Services/Keyword/KeywordService.php(61): RTool\SeoCore\Services\Keyword\Resources\GoogleAds\KeywordPlanIdeaService->getStats()
#14 /home/myproject/public/laravel/modules/seo-core/src/Services/Keyword/KeywordService.php(46): RTool\SeoCore\Services\Keyword\KeywordService->getStatsByAdsApi()
#15 /home/myproject/public/laravel/modules/keyword-gap/src/Jobs/CheckStats.php(114): RTool\SeoCore\Services\Keyword\KeywordService->getStats()
#16 /home/myproject/public/laravel/modules/keyword-gap/src/Jobs/CheckStats.php(80): RSolution\KeywordGap\Jobs\CheckStats->getKeywordStats()
#17 /home/myproject/public/laravel/modules/keyword-gap/src/Jobs/CheckStats.php(58): RSolution\KeywordGap\Jobs\CheckStats->updateKeywordStat()
#18 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): RSolution\KeywordGap\Jobs\CheckStats->handle()
#19 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#21 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#23 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#24 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#25 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#27 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#28 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#29 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#31 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#32 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#33 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#34 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process()
#35 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob()
#36 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon()
#37 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker()
#38 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#39 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#40 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#41 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#42 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#43 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#44 /home/myproject/public/laravel/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#45 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\Component\Console\Command\Command->run()
#46 /home/myproject/public/laravel/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run()
#47 /home/myproject/public/laravel/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#48 /home/myproject/public/laravel/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#49 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#50 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#51 /home/myproject/public/laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#52 {main}

**Comment by huyleresonancetech** [comment]
Hi,
I am facing the same problem. Both my server and local server are running php version 8.0.30, it runs fine on my local machine. when i run it on the server it gives the same error.

TypeError: Google\ApiCore\Middleware\RetryMiddleware::Google\ApiCore\Middleware{closure}(): Argument #1 ($e) must be of type Exception, Error given, called in /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php on line 109 and defined in /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php:183
Stack trace:
#0 /home/myproject/public/laravel/vendor/google/gax/src/Middleware/RetryMiddleware.php(109): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware{closure}()
#1 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(209): Google\ApiCore\Middleware\RetryMiddleware->Google\ApiCore\Middleware{closure}()
#2 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler()
#3 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise{closure}()
#4 /home/myproject/public/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(163): GuzzleHttp\Promise\TaskQueue->run()
#5 /home/myproject/public/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute()
#7 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /home/myproject/public/laravel/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /home/myproject/public/laravel/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/V14/Services/Gapic/KeywordPlanIdeaServiceGapicClient.php(405): GuzzleHttp\Promise\Promise->wait()
#12 /home/myproject/public/laravel/modules/my-module-core/src/Services/Keyword/Resources/GoogleAds/KeywordPlanIdeaService.php(223): Google\Ads\GoogleAds\V14\Services\Gapic\KeywordPlanIdeaServiceGapicClient->generateKeywordHistoricalMetrics()
#13 /home/myproject/public/laravel/modules/my-module-core/src/Services/Keyword/KeywordService.php(61): ToolCore\ModuleCore\Services\Keyword\Resources\GoogleAds\KeywordPlanIdeaService->getStats()
#14 /home/myproject/public/laravel/modules/my-module-core/src/Services/Keyword/KeywordService.php(46): ToolCore\ModuleCore\Services\Keyword\KeywordService->getStatsByAdsApi()
#15 /home/myproject/public/laravel/modules/my-module/src/Jobs/CheckStats.php(114): ToolCore\ModuleCore\Services\Keyword\KeywordService->getStats()
#16 /home/myproject/public/laravel/modules/my-module/src/Jobs/CheckStats.php(80): RProject\MyProject\Jobs\CheckStats->getKeywordStats()
#17 /home/myproject/public/laravel/modules/my-module/src/Jobs/CheckStats.php(58): RProject\MyProject\Jobs\CheckStats->updateKeywordStat()
#18 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): RProject\MyProject\Jobs\CheckStats->handle()
#19 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container{closure}()
#20 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#21 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#23 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#24 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus{closure}()
#25 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}()
#26 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#27 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#28 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue{closure}()
#29 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}()
#30 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#31 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#32 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#33 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#34 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process()
#35 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob()
#36 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon()
#37 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker()
#38 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#39 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container{closure}()
#40 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#41 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#42 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#43 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#44 /home/myproject/public/laravel/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#45 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\Component\Console\Command\Command->run()
#46 /home/myproject/public/laravel/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run()
#47 /home/myproject/public/laravel/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#48 /home/myproject/public/laravel/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#49 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#50 /home/myproject/public/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#51 /home/myproject/public/laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#52 {main}

**Comment by fiboknacky** [comment]
The gax-php repo has just been released last week. Could you please try again? Thanks.

**Comment by fiboknacky** [comment]
Closing due to inactivity.
